import { cookies } from 'next/headers';

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClientCookiesProvider } from './CookiesProvider'
import ThemeComponent from '@/theme/ThemeComponent';
import ThemeProvider from '@/theme/ThemeComponent';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const initialTheme = 'dark';
  const cookieStore = cookies()


  const theme = cookieStore.get('theme')?.value ?? initialTheme;
  console.log({zzx: theme});

  return (
    <ClientCookiesProvider value={cookies().getAll()}>
    <html lang="en" data-theme={theme}>
      <ThemeProvider>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
    </ClientCookiesProvider>
  )
}
